version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: fittrack-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  fittrack-backend:
    build: ./backend
    image: arjunvk/backend:v3.0.0
    container_name: fittrack-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/fittrack
      - JWT_SECRET=your_docker_secret_key
      - LOG_LEVEL=INFO
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    image: arjunvk/frontend:v3.0.0
    container_name: fittrack-frontend
    ports:
      - "3000:80"
    depends_on:
      - fittrack-backend

volumes:
  mongo-data:
