version: '3.8'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - fittrack-network
    volumes:
      - mongo-data:/data/db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  fittrack-backend:
    image: arjunvk/backend:v3.4.7
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/fittrack
      - JWT_SECRET=your_docker_secret_key
      - LOG_LEVEL=INFO
    networks:
      - fittrack-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  frontend:
    image: arjunvk/frontend:v3.4.9
    ports:
      - "80:80"
    networks:
      - fittrack-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  fittrack-network:
    driver: overlay

volumes:
  mongo-data:
