name: Deploy FitTrack Stack (Feature)

on:
  push:
    branches:
      - feature/**

concurrency:
  group: fittrack-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Deployment Info
        run: |
          echo "Deploying branch: ${{ github.ref_name }}"
          echo "Server: $(hostname)"

      - name: Remove Existing Stack
        run: |
          docker stack rm fittrack || true
          echo "Waiting for stack to be removed..."
          sleep 15

      - name: Removing unused images
        run: |
          docker image prune -f
          echo "Waiting for images to be remove..."
          sleep 15

      - name: Deploy New Stack
        run: |
          docker stack deploy -c docker-stack.yaml fittrack

      - name: Cleanup Unused Images
        run: docker image prune -f